// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  firebaseConfig: {
    apiKey: 'AIzaSyABkLiXlJzww12PmTvFmWtBsI7pfZxQNJ8',
    authDomain: 'ngx-rocket-prueba.firebaseapp.com',
    databaseURL: 'https://ngx-rocket-prueba.firebaseio.com',
    projectId: 'ngx-rocket-prueba',
    storageBucket: 'ngx-rocket-prueba.appspot.com',
    messagingSenderId: '12744109761',
    appId: '1:12744109761:web:aa4241449fe20e30eaae40',
  },
};
